# Bernouli Random Variable

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp

In [ ]:
prob = 0.3

r = tfp.distributions.Bernoulli(probs=prob, dtype=tf.float32).sample(sample_shape=(10,1))
r

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [ ]:
y_prev = tf.random.normal((10,1))
y_prev

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.41086623],
       [-0.52740365],
       [ 0.5979452 ],
       [-2.6702442 ],
       [-0.8477735 ],
       [ 0.17647636],
       [ 0.2779886 ],
       [-0.87724483],
       [-1.6221006 ],
       [-0.9711389 ]], dtype=float32)>

In [ ]:
tf.math.multiply(y_prev, r)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-0.41086623],
       [-0.        ],
       [ 0.        ],
       [-0.        ],
       [-0.        ],
       [ 0.        ],
       [ 0.        ],
       [-0.        ],
       [-0.        ],
       [-0.        ]], dtype=float32)>

# Dropout layer

In [ ]:
from tensorflow import keras

In [ ]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[28, 28]),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(300, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(100, activation="elu", kernel_initializer="he_normal"),
    keras.layers.Dropout(rate=0.5),
    keras.layers.Dense(10, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam", metrics=["accuracy"])
# n_epochs = 2
# history = model.fit(X_train_scaled, y_train, epochs=n_epochs,
#                     validation_data=(X_valid_scaled, y_valid))

In [ ]:
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dropout (Dropout)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 300)               235500    
                                                                 
 dropout_1 (Dropout)         (None, 300)               0         
                                                                 
 dense_1 (Dense)             (None, 100)               30100     
                                                                 
 dropout_2 (Dropout)         (None, 100)               0         
                                                                 
 dense_2 (Dense)             (None, 10)                1

In [ ]:
layer = tf.keras.layers.Dropout(.3, input_shape=(1,))

In [ ]:
layer

In [ ]:
data = tf.random.normal((10,1))
data

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-1.8717328 ],
       [-0.3042993 ],
       [ 1.1353676 ],
       [-2.7305198 ],
       [-0.27882499],
       [-0.88339365],
       [-1.260125  ],
       [-1.4305468 ],
       [ 0.13017027],
       [-0.16652448]], dtype=float32)>

In [ ]:
layer(data, training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[-2.6739042 ],
       [-0.        ],
       [ 1.6219538 ],
       [-3.9007425 ],
       [-0.39832142],
       [-0.        ],
       [-1.8001786 ],
       [-0.        ],
       [ 0.        ],
       [-0.23789212]], dtype=float32)>

In [ ]:
l = tf.keras.layers.Dropout(.1, input_shape=(1,))

In [ ]:
d = tf.ones((10,1))*5
d

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.],
       [5.]], dtype=float32)>

In [ ]:
l(d, training=True)

<tf.Tensor: shape=(10, 1), dtype=float32, numpy=
array([[5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [5.555556],
       [0.      ],
       [5.555556],
       [0.      ],
       [5.555556]], dtype=float32)>

In [ ]:
5*(1/(1-0.1))

5.555555555555555